### ISSUE TITLE
External links

### ISSUE THREAD

**Issue by mdardir2002** [AbdulSheikh/Spider#1]
I'm new to python so excuse my ignorance...
You know how is the spider finds all internal links on page and store them in the queue file to be crawled later for more links and so on .... I'm trying to make the spider also save all unique external links in another file called external . Any help!!
@AbdulSheikh

**Comment by AbdulSheikh** [comment]
I will work on that. That should be done within 24 hours.Thanks for the contribution.

**Comment by mdardir2002** [comment]
Great looking forward thanks

**Comment by AbdulSheikh** [comment]
Issue has been fixed. A new version has been released. Please check if your problem was solved.

**Comment by mdardir2002** [comment]
Thanks for being super fast to do this . which Python version I should use as a interpreter ?? I'm running 
pycharm  and I tried using python 3.6.1 or 2.7.13 but I'm running to errors

**Comment by AbdulSheikh** [comment]
Python 3.6+
