### ISSUE TITLE
Politeness Time

### ISSUE THREAD

**Issue by kamranabdullazade** [AbdulSheikh/Spider#13]
Hello, Where should we add Politeness Time for effective work?

**Comment by mdardir2002** [comment]
well there is couple ways you need to be polite.
1-  let's say when you load a web page with a download link  that will be not available till a time pass by like 30 sec. so you want to use multi-threads for speed to request the page and then wait for 30 sec and then scrape link.... and so on.
2- if you flood website with one request after another some web hosting providers will  interrupt service for the website as a protection for there resources or your IP can even get blacklisted from ever seeing that website again.
