### ISSUE TITLE
Spider issue (get_domain_name(url):) not found anywhere else

### ISSUE THREAD

**Issue by tutu86** [AbdulSheikh/Spider#4]
in the spider page there is a code saying : 

@staticmethod
    def add_links_to_queue(links):
        for url in links:
            if (url in Spider.queue) or (url in Spider.crawled):
                continue
            if Spider.domain_name != get_domain_name(url):
                continue
            Spider.queue.add(url)

But there is no such a mention anywhere for "get_domain_name" method. Is this a Python 2 vs 3 problem or its just me?

**Comment by AbdulSheikh** [comment]
get_domain_name is a method located in domain.py file
