### ISSUE TITLE
Read me 

### ISSUE THREAD

**Issue by mdardir2002** [AbdulSheikh/Spider#5]
Is it possible to explain in the read me file what is best setup and the way to run this spider with examples and expected results please. Thanks

**Comment by AbdulSheikh** [comment]
Sorry for the late reply. The problem is being worked on as we speak. The update should i make within 48 hours. Thank you for your contribution.

**Comment by AbdulSheikh** [comment]
The program has been updated, Please check if the issue has been resolved. We hope you are satisfied. Please reply within 3 days else the issue will be considered solved.

**Comment by AbdulSheikh** [comment]
The issue is considered solved. The case is being terminated
