### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by jon7899** [AbdulSheikh/Spider#7]
I'm getting the following KeyError when trying to run this.  My first rough guess would be that this could have something to do with the caret character, but I'm really not sure why this is breaking.
Error feeds back as follows:
Please enter Project name: Test
Please enter the url to crawl: www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=POSTCODE^783018
Please enter the directory path where the queue and crawled txt files will be store: 
C:/Users/jonat/Desktop/est
C:/Users/jonat/Desktop/Test/queue.txt
C:/Users/jonat/Desktop/Test/crawled.txt
www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=POSTCODE^783018
Traceback (most recent call last):
  File "C:/Users/jonat/PycharmProjects/BespokeCrawler/main.py", line 18, in <module>
    Spider(PROJECT_NAME, Requirement_Manager.getHomePage(), DOMAIN_NAME)
  File "C:\Users\jonat\PycharmProjects\BespokeCrawler\spider.py", line 24, in __init__
    self.crawl_page('First spider', Spider.base_url)
  File "C:\Users\jonat\PycharmProjects\BespokeCrawler\spider.py", line 40, in crawl_page
    Spider.queue.remove(page_url)
KeyError: 'www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=POSTCODE^783018'

Process finished with exit code 1

**Comment by AbdulSheikh** [comment]
I will take a look. Updates should be pushed out within few days

**Comment by AbdulSheikh** [comment]
Updates have been pushed out.
Make sure to use: https:// in front of the url
https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=POSTCODE^783018
